from __future__ import annotations

import json
import hashlib
import re
import shutil
from pathlib import Path
from typing import Any

from .build_preflight import enforce_build_preflight


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _write_runtime_contract(runtime_dist: Path, output_dir: Path) -> Path:
    source = runtime_dist / "runtime-contract.json"
    if not source.is_file():
        raise FileNotFoundError("Runtime conformance metadata is missing. Run the frontend production build first.")
    try:
        contract = json.loads(source.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise ValueError("Runtime conformance metadata is invalid") from error
    block_types = contract.get("blockTypes")
    if contract.get("schemaVersion") != 1 or not contract.get("matrixVersion") or not isinstance(block_types, list) or len(block_types) != 13:
        raise ValueError("Runtime conformance metadata does not describe the 13 Block matrix")
    contract["bundles"] = {
        name: {"sha256": _sha256_file(output_dir / name), "bytes": (output_dir / name).stat().st_size}
        for name in ("player.js", "player.css", "project.js")
    }
    destination = output_dir / "runtime-contract.json"
    destination.write_text(json.dumps(contract, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    return destination


def safe_slug(value: str) -> str:
    slug = re.sub(r"[^\w\-\u4e00-\u9fff]+", "-", value.strip()).strip("-")
    return slug or "slide-game"


def renpy_identifier(value: str) -> str:
    normalized = re.sub(r"\W+", "_", value, flags=re.UNICODE).strip("_")
    if not normalized or not normalized[0].isalpha():
        normalized = f"label_{normalized}"
    return normalized.lower()


def quote(value: Any) -> str:
    return json.dumps(str(value or ""), ensure_ascii=False)


def python_literal(value: Any) -> str:
    return repr(value)


def export_renpy(project: dict[str, Any], output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    enabled_chapters = [chapter for chapter in project["chapters"] if not chapter.get("disabled")]
    fragment_names = {
        fragment["id"]: renpy_identifier(fragment["id"])
        for chapter in enabled_chapters for fragment in chapter.get("fragments", [])
    }
    character_names = sorted({
        block.get("speaker") for blocks in project["scripts"].values()
        for block in blocks if block.get("type") == "dialogue" and block.get("speaker")
    })
    character_ids = {name: f"char_{index}" for index, name in enumerate(character_names, 1)}
    lines = ["# Generated by Slide Studio", "", "default _slide_vars = {}", ""]
    for name, identifier in character_ids.items():
        lines.append(f"define {identifier} = Character({quote(name)})")
    lines.extend(["", "label start:"])
    entry_chapter = enabled_chapters[0] if enabled_chapters else None
    entry_fragment = entry_chapter["fragments"][0] if entry_chapter and entry_chapter.get("fragments") else None
    if entry_fragment is None:
        raise ValueError("没有可导出的片段：请确认至少有一个未禁用章节包含片段")
    entry_fragment_id = entry_fragment["id"]
    lines.extend([f"    call {fragment_names[entry_fragment_id]}", "    return", ""])
    for chapter in enabled_chapters:
        lines.append(f"# {chapter['name']}")
        for fragment in chapter.get("fragments", []):
            lines.append(f"label {fragment_names[fragment['id']]}:")
            blocks = project["scripts"].get(fragment["id"], [])
            if not blocks:
                lines.append("    pass")
            for block in blocks:
                block_type = block.get("type")
                if block_type == "narration":
                    lines.append(f"    {quote(block.get('text'))}")
                elif block_type == "dialogue":
                    speaker = character_ids.get(block.get("speaker"), "narrator")
                    lines.append(f"    {speaker} {quote(block.get('text'))}")
                elif block_type == "scene":
                    lines.append(f"    # scene {block.get('title', '')} with {block.get('transition', 'dissolve')}")
                elif block_type == "sound":
                    lines.append(f"    play music {quote(block.get('title'))} {'loop' if block.get('loop') else ''}".rstrip())
                elif block_type == "branch":
                    lines.append(f"    menu {quote(block.get('title', '请选择'))}:")
                    for option in block.get("options", []):
                        target = fragment_names.get(option.get("target"))
                        lines.append(f"        {quote(option.get('text'))}:")
                        lines.append(f"            {'call ' + target if target else 'pass'}")
                elif block_type == "setVariable":
                    lines.append(f"    $ _slide_vars[{quote(block.get('variable'))}] = {python_literal(block.get('value'))}")
                elif block_type == "condition":
                    operators = {"eq": "==", "neq": "!=", "gt": ">", "gte": ">=", "lt": "<", "lte": "<="}
                    operator = operators.get(block.get("operator"), "==")
                    lines.append(f"    if _slide_vars.get({quote(block.get('variable'))}) {operator} {python_literal(block.get('compareValue'))}:")
                    true_target = fragment_names.get(block.get("trueTarget"))
                    lines.append(f"        {'jump ' + true_target if true_target else 'pass'}")
                    false_target = fragment_names.get(block.get("falseTarget"))
                    if false_target:
                        lines.extend(["    else:", f"        jump {false_target}"])
                elif block_type in {"jump", "call"}:
                    target = fragment_names.get(block.get("target"))
                    lines.append(f"    {block_type + ' ' + target if target else 'pass'}")
                elif block_type == "return":
                    lines.append("    return")
            lines.extend(["    return", ""])
    output = output_dir / "script.rpy"
    output.write_text("\n".join(lines), encoding="utf-8")
    return output


PLAYER_HTML = """<!doctype html>
<html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#111719"><title>Slide Game</title><link rel="stylesheet" href="player.css"></head>
<body><div id="game-root"></div><script src="project.js"></script><script src="player.js"></script></body></html>"""




def _referenced_asset_ids(project: dict[str, Any]) -> set[str]:
    assets = project.get("assets", [])
    by_name: dict[str, str] = {}
    by_id: set[str] = set()
    for asset in assets:
        asset_id = str(asset.get("id", ""))
        by_id.add(asset_id)
        by_name[str(asset.get("name", ""))] = asset_id
        by_name[Path(str(asset.get("path", ""))).name] = asset_id
    referenced = {str(asset.get("id")) for asset in assets if asset.get("forceBundle")}
    title = project.get("ui", {}).get("title", {})
    referenced.update(str(asset_id) for asset_id in (title.get("backgroundAssetId"), title.get("logoAssetId")) if asset_id)
    runtime_theme = project.get("ui", {}).get("runtimeTheme", {})
    if runtime_theme.get("fontAssetId"):
        referenced.add(str(runtime_theme["fontAssetId"]))
    for character in project.get("characters", []):
        referenced.update(str(asset_id) for asset_id in character.get("portraits", {}).values() if asset_id)
        referenced.update(str(overlay["assetId"]) for overlay in character.get("overlays", []) if overlay.get("assetId"))
    for blocks in project.get("scripts", {}).values():
        for block in blocks:
            if block.get("assetId"):
                referenced.add(str(block["assetId"]))
            for layer in block.get("layers", []):
                if layer.get("assetId"):
                    referenced.add(str(layer["assetId"]))
            voice = str(block.get("voice", ""))
            if voice in by_id:
                referenced.add(voice)
            elif voice and voice in by_name:
                referenced.add(by_name[voice])
    for timeline in project.get("timelines", {}).values():
        for track in timeline.get("tracks", []):
            for clip in track.get("clips", []):
                if clip.get("assetId"):
                    referenced.add(str(clip["assetId"]))
    return referenced


def build_web_game(
    project: dict[str, Any],
    output_dir: Path,
    project_path: Path,
    builtin_assets: Path,
    custom_assets: Path | None = None,
    runtime_dist: Path | None = None,
    target: str = "web",
) -> Path:
    if runtime_dist is None:
        raise ValueError("Web runtime directory is required")
    runtime_js = runtime_dist / "player.js"
    runtime_css = runtime_dist / "player.css"
    if not runtime_js.is_file() or not runtime_css.is_file():
        raise FileNotFoundError("Shared engine-core runtime is missing. Run the frontend production build first.")
    custom_asset_dir = custom_assets or project_path.parent / f"{project_path.stem}.assets"
    enforce_build_preflight(project, target, builtin_assets, custom_asset_dir)
    if output_dir.exists():
        shutil.rmtree(output_dir)
    assets_dir = output_dir / "assets"
    assets_dir.mkdir(parents=True, exist_ok=True)
    exported = json.loads(json.dumps(project, ensure_ascii=False))
    exported.pop("productionMemory", None)
    enabled_fragment_ids = {
        fragment["id"]
        for chapter in exported.get("chapters", []) if not chapter.get("disabled")
        for fragment in chapter.get("fragments", [])
    }
    exported["chapters"] = [chapter for chapter in exported.get("chapters", []) if not chapter.get("disabled")]
    exported["scripts"] = {
        fragment_id: blocks for fragment_id, blocks in exported.get("scripts", {}).items()
        if fragment_id in enabled_fragment_ids
    }
    exported["timelines"] = {
        fragment_id: timeline for fragment_id, timeline in exported.get("timelines", {}).items()
        if fragment_id in enabled_fragment_ids
    }
    if exported.get("activeFragmentId") not in enabled_fragment_ids and enabled_fragment_ids:
        exported["activeFragmentId"] = next(iter(enabled_fragment_ids))
    referenced_ids = _referenced_asset_ids(exported)
    exported["assets"] = [asset for asset in exported.get("assets", []) if str(asset.get("id")) in referenced_ids]
    for asset in exported.get("assets", []):
        source: Path | None = None
        path_value = str(asset.get("path", ""))
        if path_value.startswith("builtin/") or (path_value.startswith("assets/") and (builtin_assets / Path(path_value).name).is_file()):
            source = builtin_assets / Path(path_value).name
        elif path_value:
            source = custom_asset_dir / Path(path_value).name
        if source and source.is_file():
            destination = assets_dir / source.name
            shutil.copy2(source, destination)
            asset["exportPath"] = f"assets/{destination.name}"
            asset["uri"] = asset["exportPath"]
        else:
            asset.pop("uri", None)
    (output_dir / "index.html").write_text(PLAYER_HTML, encoding="utf-8")
    shutil.copy2(runtime_css, output_dir / "player.css")
    shutil.copy2(runtime_js, output_dir / "player.js")
    (output_dir / "project.js").write_text("window.SLIDE_PROJECT=" + json.dumps(exported, ensure_ascii=False) + ";", encoding="utf-8")
    _write_runtime_contract(runtime_dist, output_dir)
    return output_dir / "index.html"
