from __future__ import annotations

import json
import re
import shutil
from pathlib import Path
from typing import Any


def safe_slug(value: str) -> str:
    slug = re.sub(r"[^\w\-\u4e00-\u9fff]+", "-", value.strip()).strip("-")
    return slug or "hikari-game"


def renpy_identifier(value: str) -> str:
    normalized = re.sub(r"\W+", "_", value, flags=re.UNICODE).strip("_")
    if not normalized or not normalized[0].isalpha():
        normalized = f"label_{normalized}"
    return normalized.lower()


def quote(value: Any) -> str:
    return json.dumps(str(value or ""), ensure_ascii=False)


def python_literal(value: Any) -> str:
    return repr(value)


def export_renpy(project: dict[str, Any], output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    enabled_chapters = [chapter for chapter in project["chapters"] if not chapter.get("disabled")]
    fragment_names = {
        fragment["id"]: renpy_identifier(fragment["id"])
        for chapter in enabled_chapters for fragment in chapter.get("fragments", [])
    }
    character_names = sorted({
        block.get("speaker") for blocks in project["scripts"].values()
        for block in blocks if block.get("type") == "dialogue" and block.get("speaker")
    })
    character_ids = {name: f"char_{index}" for index, name in enumerate(character_names, 1)}
    lines = ["# Generated by Hikari Studio", "", "default _hikari_vars = {}", ""]
    for name, identifier in character_ids.items():
        lines.append(f"define {identifier} = Character({quote(name)})")
    lines.extend(["", "label start:"])
    entry_fragment = enabled_chapters[0]["fragments"][0]["id"]
    lines.extend([f"    call {fragment_names[entry_fragment]}", "    return", ""])
    for chapter in enabled_chapters:
        lines.append(f"# {chapter['name']}")
        for fragment in chapter.get("fragments", []):
            lines.append(f"label {fragment_names[fragment['id']]}:")
            blocks = project["scripts"].get(fragment["id"], [])
            if not blocks:
                lines.append("    pass")
            for block in blocks:
                block_type = block.get("type")
                if block_type == "narration":
                    lines.append(f"    {quote(block.get('text'))}")
                elif block_type == "dialogue":
                    speaker = character_ids.get(block.get("speaker"), "narrator")
                    lines.append(f"    {speaker} {quote(block.get('text'))}")
                elif block_type == "scene":
                    lines.append(f"    # scene {block.get('title', '')} with {block.get('transition', 'dissolve')}")
                elif block_type == "sound":
                    lines.append(f"    play music {quote(block.get('title'))} {'loop' if block.get('loop') else ''}".rstrip())
                elif block_type == "branch":
                    lines.append(f"    menu {quote(block.get('title', '请选择'))}:")
                    for option in block.get("options", []):
                        target = fragment_names.get(option.get("target"))
                        lines.append(f"        {quote(option.get('text'))}:")
                        lines.append(f"            {'call ' + target if target else 'pass'}")
                elif block_type == "setVariable":
                    lines.append(f"    $ _hikari_vars[{quote(block.get('variable'))}] = {python_literal(block.get('value'))}")
                elif block_type == "condition":
                    operators = {"eq": "==", "neq": "!=", "gt": ">", "gte": ">=", "lt": "<", "lte": "<="}
                    operator = operators.get(block.get("operator"), "==")
                    lines.append(f"    if _hikari_vars.get({quote(block.get('variable'))}) {operator} {python_literal(block.get('compareValue'))}:")
                    true_target = fragment_names.get(block.get("trueTarget"))
                    lines.append(f"        {'jump ' + true_target if true_target else 'pass'}")
                    false_target = fragment_names.get(block.get("falseTarget"))
                    if false_target:
                        lines.extend(["    else:", f"        jump {false_target}"])
                elif block_type in {"jump", "call"}:
                    target = fragment_names.get(block.get("target"))
                    lines.append(f"    {block_type + ' ' + target if target else 'pass'}")
                elif block_type == "return":
                    lines.append("    return")
            lines.extend(["    return", ""])
    output = output_dir / "script.rpy"
    output.write_text("\n".join(lines), encoding="utf-8")
    return output


PLAYER_HTML = """<!doctype html>
<html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#111719"><title>Hikari Game</title><link rel="stylesheet" href="player.css"></head>
<body><div id="game-root"></div><script src="project.js"></script><script src="player.js"></script></body></html>"""

PLAYER_CSS = """*{box-sizing:border-box}html,body{margin:0;height:100%;background:#111;font-family:system-ui,sans-serif}#game{height:100%;position:relative;overflow:hidden;background:#1b252a}#background{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}#scene-layers,#characters{position:absolute;inset:0}#scene-layers img{position:absolute;width:100%;height:100%;object-fit:contain;pointer-events:none}#characters img{position:absolute;bottom:0;height:88%;width:30%;object-fit:contain;object-position:bottom;transform:translateX(-50%);pointer-events:none}#shade{position:absolute;inset:0;background:linear-gradient(transparent 45%,rgba(0,0,0,.65))}#dialogue{position:absolute;left:7%;right:7%;bottom:7%;padding:22px 26px;background:rgba(248,250,250,.94);border-left:5px solid #187c6b;box-shadow:0 10px 35px #0007;min-height:130px}#speaker{color:#126556;font-size:18px}#text{font-size:20px;line-height:1.7;margin:8px 0 0}#next{position:absolute;right:18px;bottom:12px;color:#187c6b}#choices{display:grid;gap:8px}#choices button{border:1px solid #b7c3c6;background:white;padding:12px 15px;text-align:left;font-size:16px;cursor:pointer}#choices button:hover{border-color:#187c6b;background:#e8f4f1}@media(max-width:700px){#dialogue{left:3%;right:3%;bottom:3%;padding:16px}#text{font-size:16px}}"""

PLAYER_JS = """const p=window.HIKARI_PROJECT;
const bg=document.querySelector('#background'),sceneLayers=document.querySelector('#scene-layers'),characters=document.querySelector('#characters'),speaker=document.querySelector('#speaker'),text=document.querySelector('#text'),choices=document.querySelector('#choices'),next=document.querySelector('#next');
let fragment=p.chapters[0].fragments[0].id,index=0,currentBg='',variables={...(p.variables||{})},callStack=[];
const audioChannels={bgm:new Audio(),sfx:new Audio(),voice:new Audio()};
function blocks(){return p.scripts[fragment]||[]}
function asset(id){return p.assets.find(a=>a.id===id)}
function audioAsset(value){return p.assets.find(a=>a.id===value||a.name===value||(a.path||'').endsWith(value||''))}
function playAudio(b){const channel=b.channel||'bgm',player=audioChannels[channel]||audioChannels.sfx;if((b.action||'play')==='stop'){player.pause();return}const a=audioAsset(b.assetId||b.title);if(!a)return;player.src=a.exportPath||a.uri||a.path;player.volume=Math.max(0,Math.min(1,b.volume??1));player.loop=b.loop??channel==='bgm';player.play().catch(()=>{})}
function character(id){return (p.characters||[]).find(c=>c.id===id)}
function characterBySpeaker(value){return (p.characters||[]).find(c=>c.id===value||c.name===value)}
function dimension(value){return value&&value.value!=null?value.value+(value.unit||'px'):''}
function displayName(b,c){if(!c)return b.speaker||'';const scheme=(c.displayNameSchemes||[]).find(s=>s.id===b.displayNameSchemeId);if(!scheme)return c.name;const value=scheme.kind==='fixed'?scheme.value:scheme.kind==='variable'?variables[scheme.value]:(c.attributes||{})[scheme.value];return String(value??'').trim()||c.name}
function syncOverlays(c,img){characters.querySelectorAll(`[data-overlay-owner="${c.id}"]`).forEach(item=>item.remove());(c.overlays||[]).forEach(o=>{const a=asset(o.assetId);if(!a)return;const layer=document.createElement('img');layer.className='character-overlay';layer.dataset.overlayOwner=c.id;layer.src=a.exportPath||a.uri||a.path;layer.alt=o.name||'';layer.style.left=img.style.left;layer.style.opacity=o.opacity??1;layer.style.scale=img.style.scale;layer.style.zIndex=(o.layer??0)+(c.defaultLayer??0)+21;if(o.overrideSize){layer.style.width=dimension(o.width);layer.style.height=dimension(o.height)}characters.appendChild(layer)})}
function applyCharacter(img,c,b={}){const position=b.position??c.defaultPosition??'center';img.style.left=({farLeft:10,left:28,center:50,right:72,farRight:90}[position]??b.x??50)+'%';img.style.opacity=b.opacity??1;img.style.scale=b.scale??c.defaultScale??1;img.style.zIndex=(b.layer??c.defaultLayer??0)+20;img.style.width=dimension(c.portraitWidth);img.style.height=dimension(c.portraitHeight);syncOverlays(c,img)}
function fail(message){speaker.textContent='运行时错误';text.textContent=message;next.hidden=true}
function go(target){if(!target||!p.scripts[target]){fail('无效的片段目标：'+(target||'未设置'));return false}fragment=target;index=0;return true}
function compare(left,op,right){if(op==='neq')return left!==right;if(op==='gt')return Number(left)>Number(right);if(op==='gte')return Number(left)>=Number(right);if(op==='lt')return Number(left)<Number(right);if(op==='lte')return Number(left)<=Number(right);return left===right}
function render(){choices.innerHTML='';next.hidden=false;for(let guard=0;guard<1000;guard++){
  const list=blocks();if(index>=list.length){if(callStack.length){const frame=callStack.pop();fragment=frame.fragment;index=frame.index;continue}speaker.textContent='';text.textContent='游戏结束';next.hidden=true;return}
  const b=list[index];
  if(b.type==='scene'){const a=asset(b.assetId);if(a){currentBg=a.exportPath||a.uri||a.path;bg.src=currentBg}sceneLayers.innerHTML='';(b.layers||[]).sort((x,y)=>(x.layer||0)-(y.layer||0)).forEach(l=>{const la=asset(l.assetId);if(!la)return;const img=document.createElement('img');img.src=la.exportPath||la.uri||la.path;img.alt=l.name||'';img.style.left=(l.x??50)+'%';img.style.top=(l.y??50)+'%';img.style.opacity=l.opacity??1;img.style.transform=`translate(-50%,-50%) scale(${l.scale??1})`;img.style.mixBlendMode=l.blendMode||'normal';img.style.zIndex=l.layer||0;sceneLayers.appendChild(img)});index++;continue}
  if(b.type==='characterShow'){const c=character(b.characterId),expression=b.expression||'默认',a=asset(b.assetId||(c&&c.portraits&&c.portraits[expression]));let img=characters.querySelector(`[data-character="${b.characterId}"]`);if(!img){img=document.createElement('img');img.dataset.character=b.characterId;characters.appendChild(img)}if(a)img.src=a.exportPath||a.uri||a.path;img.alt=((c&&c.name)||b.characterId)+' · '+expression;if(c)applyCharacter(img,c,b);index++;continue}
  if(b.type==='characterHide'){characters.querySelectorAll(`[data-character="${b.characterId}"],[data-overlay-owner="${b.characterId}"]`).forEach(item=>item.remove());index++;continue}
  if(b.type==='sound'){playAudio(b);index++;continue}
  if(b.type==='setVariable'){if(b.variable)variables[b.variable]=b.value;index++;continue}
  if(b.type==='jump'){if(!go(b.target))return;continue}
  if(b.type==='condition'){const target=compare(variables[b.variable],b.operator,b.compareValue)?b.trueTarget:b.falseTarget;if(target&&!go(target))return;if(!target)index++;continue}
  if(b.type==='call'){callStack.push({fragment,index:index+1});if(!go(b.target))return;continue}
  if(b.type==='return'){if(!callStack.length){speaker.textContent='';text.textContent='游戏结束';next.hidden=true;return}const frame=callStack.pop();fragment=frame.fragment;index=frame.index;continue}
  if(b.type==='branch'){speaker.textContent=b.title||'请选择';text.textContent='';next.hidden=true;(b.options||[]).forEach(o=>{const button=document.createElement('button');button.textContent=o.text;button.onclick=e=>{e.stopPropagation();if(!go(o.target))return;render()};choices.appendChild(button)});return}
  if(b.type==='dialogue'){const c=characterBySpeaker(b.speaker),expression=b.expression||(c&&c.expressions&&c.expressions[0])||'默认',a=asset(c&&c.portraits&&c.portraits[expression]);if(c&&a){let img=characters.querySelector(`[data-character="${c.id}"]`);if(!img){img=document.createElement('img');img.dataset.character=c.id;characters.appendChild(img)}img.src=a.exportPath||a.uri||a.path;img.alt=c.name+' · '+expression;applyCharacter(img,c)}if(b.voice)playAudio({channel:'voice',assetId:b.voice});speaker.textContent=displayName(b,c)}else speaker.textContent='';text.textContent=b.text||'';return
}fail('流程执行超过 1000 步，可能存在无限循环')}
document.querySelector('#game').onclick=()=>{if(choices.children.length)return;index++;render()};render();"""


def _referenced_asset_ids(project: dict[str, Any]) -> set[str]:
    assets = project.get("assets", [])
    by_name: dict[str, str] = {}
    by_id: set[str] = set()
    for asset in assets:
        asset_id = str(asset.get("id", ""))
        by_id.add(asset_id)
        by_name[str(asset.get("name", ""))] = asset_id
        by_name[Path(str(asset.get("path", ""))).name] = asset_id
    referenced = {str(asset.get("id")) for asset in assets if asset.get("forceBundle")}
    title = project.get("ui", {}).get("title", {})
    referenced.update(str(asset_id) for asset_id in (title.get("backgroundAssetId"), title.get("logoAssetId")) if asset_id)
    runtime_theme = project.get("ui", {}).get("runtimeTheme", {})
    if runtime_theme.get("fontAssetId"):
        referenced.add(str(runtime_theme["fontAssetId"]))
    for character in project.get("characters", []):
        referenced.update(str(asset_id) for asset_id in character.get("portraits", {}).values() if asset_id)
        referenced.update(str(overlay["assetId"]) for overlay in character.get("overlays", []) if overlay.get("assetId"))
    for blocks in project.get("scripts", {}).values():
        for block in blocks:
            if block.get("assetId"):
                referenced.add(str(block["assetId"]))
            for layer in block.get("layers", []):
                if layer.get("assetId"):
                    referenced.add(str(layer["assetId"]))
            voice = str(block.get("voice", ""))
            if voice in by_id:
                referenced.add(voice)
            elif voice and voice in by_name:
                referenced.add(by_name[voice])
    return referenced


def build_web_game(
    project: dict[str, Any],
    output_dir: Path,
    project_path: Path,
    builtin_assets: Path,
    custom_assets: Path | None = None,
    runtime_dist: Path | None = None,
) -> Path:
    if runtime_dist is None:
        raise ValueError("Web runtime directory is required")
    runtime_js = runtime_dist / "player.js"
    runtime_css = runtime_dist / "player.css"
    if not runtime_js.is_file() or not runtime_css.is_file():
        raise FileNotFoundError("Shared engine-core runtime is missing. Run the frontend production build first.")
    if output_dir.exists():
        shutil.rmtree(output_dir)
    assets_dir = output_dir / "assets"
    assets_dir.mkdir(parents=True, exist_ok=True)
    exported = json.loads(json.dumps(project, ensure_ascii=False))
    enabled_fragment_ids = {
        fragment["id"]
        for chapter in exported.get("chapters", []) if not chapter.get("disabled")
        for fragment in chapter.get("fragments", [])
    }
    exported["chapters"] = [chapter for chapter in exported.get("chapters", []) if not chapter.get("disabled")]
    exported["scripts"] = {
        fragment_id: blocks for fragment_id, blocks in exported.get("scripts", {}).items()
        if fragment_id in enabled_fragment_ids
    }
    if exported.get("activeFragmentId") not in enabled_fragment_ids and enabled_fragment_ids:
        exported["activeFragmentId"] = next(iter(enabled_fragment_ids))
    referenced_ids = _referenced_asset_ids(exported)
    exported["assets"] = [asset for asset in exported.get("assets", []) if str(asset.get("id")) in referenced_ids]
    custom_asset_dir = custom_assets or project_path.parent / f"{project_path.stem}.assets"
    for asset in exported.get("assets", []):
        source: Path | None = None
        path_value = str(asset.get("path", ""))
        if path_value.startswith("builtin/") or (path_value.startswith("assets/") and (builtin_assets / Path(path_value).name).is_file()):
            source = builtin_assets / Path(path_value).name
        elif path_value:
            source = custom_asset_dir / Path(path_value).name
        if source and source.is_file():
            destination = assets_dir / source.name
            shutil.copy2(source, destination)
            asset["exportPath"] = f"assets/{destination.name}"
            asset["uri"] = asset["exportPath"]
        else:
            asset.pop("uri", None)
    (output_dir / "index.html").write_text(PLAYER_HTML, encoding="utf-8")
    shutil.copy2(runtime_css, output_dir / "player.css")
    shutil.copy2(runtime_js, output_dir / "player.js")
    (output_dir / "project.js").write_text("window.HIKARI_PROJECT=" + json.dumps(exported, ensure_ascii=False) + ";", encoding="utf-8")
    return output_dir / "index.html"
